#!/usr/bin/env python

"""Usage:
   maps_build_manfest -
"""

import csv, json, os, re, sys
import xml.etree.ElementTree as ElementTree
from classes import MapsIIIFManifest
from docopt import docopt


if __name__ == '__main__':
    arguments = docopt(__doc__)
    print(MapsIIIFManifest(sys.stdin.read()))
