#!/usr/bin/env python

"""
Utility script to split a sequence of MARCXML records into individual files-
e.g., for testing the Social Scientists Maps Collection.
"""


import sys
import xml.etree.ElementTree as ElementTree

ElementTree.register_namespace('', 'http://www.loc.gov/MARC21/slim')

x = ElementTree.parse('VuFindExport-3.xml')

for record in x.findall("{http://www.loc.gov/MARC21/slim}record"):
    identifier = record.find("{http://www.loc.gov/MARC21/slim}datafield[@tag='856']/{http://www.loc.gov/MARC21/slim}subfield[@code='u']").text.split('/').pop()

    with open('{}.xml'.format(identifier), 'w') as f:
        f.write(ElementTree.tostring(record).decode('utf-8'))
